org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
version=2026.12.0
group=com.github.epsilon

# Common
mod_id=epsilon
mod_name=Epsilon
mod_author=Chen_Meng, 06789
license=GPL-3.0-only
description=A powerful cheat mod for Minecraft
